package com.tweetapp.model;

import java.util.Date;
import java.util.List;

import javax.validation.constraints.NotBlank;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Tweet")
public class Tweet {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	@NotBlank
	@DynamoDBAttribute
	private String loginID;
	@NotBlank
	@DynamoDBAttribute
	private String tweetMessage;
	@DynamoDBAttribute
	private Date createdDate;
	@DynamoDBAttribute
	private Date modifiedDate;
	@DynamoDBAttribute
	private List<Reply> reply;
	@DynamoDBAttribute
	private List<String> likes;

	public String getLoginID() {
		return loginID;
	}

	public void setLoginID(String loginID) {
		this.loginID = loginID;
	}

	public List<String> getLikes() {
		return likes;
	}

	public void setLikes(List<String> likes) {
		this.likes = likes;
	}

	public List<Reply> getReply() {
		return reply;
	}

	public void setReply(List<Reply> reply) {
		this.reply = reply;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTweetMessage() {
		return tweetMessage;
	}

	public void setTweetMessage(String tweetMessage) {
		this.tweetMessage = tweetMessage;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getModifiedDate() {
		return modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
