package com.tweetapp.model;

import javax.validation.constraints.NotBlank;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName = "User")
public class User {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	@NotBlank
	@DynamoDBAttribute
	private String firstName;
	@NotBlank
	@DynamoDBAttribute
	private String lastName;
	@NotBlank
	@DynamoDBAttribute
	private String email;
	@NotBlank
	@DynamoDBAttribute
	private String password;
	@NotBlank
	@DynamoDBAttribute
	private String confirmPassword;
	@NotBlank
	@DynamoDBAttribute
	private String contactNumber;
	@NotBlank
	@DynamoDBAttribute
	private String loginID;

	
	 public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}


	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}


	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getConfirmPassword() {
		return confirmPassword;
	}

	public void setConfirmPassword(String confirmPassword) {
		this.confirmPassword = confirmPassword;
	}

	
	public String getContactNumber() {
		return contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}


	public String getLoginID() {
		return loginID;
	}

	public void setLoginID(String loginID) {
		this.loginID = loginID;
	}

}
